[BUGFIX] Minor bug fixes while reading config.properties file
blackrock/ingen pull request #48
Opened 2024-07-01 12:24 UTC by Om-Gujarathi

## Description
Fixes - #6 and #7 

## Changes Made

1. Used the `with` statement to ensure the file is closed properly after reading.
2. Used a `try` block to handle `FileNotFoundError` and other exceptions gracefully.
3. Added a condition `if prop.strip():` to skip empty lines.

## Definition of Done

Before submitting this pull request, please ensure that the following criteria have been met:

- [x] All automated tests have passed successfully.
- [x] All manual tests have passed successfully.
- [x] Code has been reviewed by at least one other team member.
- [x] Code has been properly documented and commented as needed.
- [x] All new and existing code adheres to our project's coding standards.
- [x] All dependencies have been added or removed from the project's README or other documentation as needed.
- [x] Any relevant documentation or help files have been updated to reflect the changes made in this pull request.
- [x] Any necessary database migrations have been run.
- [x] Any relevant UI changes have been reviewed and approved by the UI/UX team.

2024-08-30 19:42 UTC, shpiyu requested changes
Thanks for your contribution Om, I've run the run code locally and it fixes both the issues. Thanks a lot. Could you please remove the print statement and then we can merge the PR.

2024-08-30 19:42 UTC, shpiyu commented on ingen/utils/properties.py
> +                                print(prop)
you may remove this `print` statement

2024-08-30 19:59 UTC, shpiyu requested changes
Thank you!

2024-08-30 19:59 UTC, shpiyu approved these changes

2024-09-02 11:30 UTC, Jatin-8898 approved these changes

2024-09-02 11:30 UTC, merged

2024-09-02 16:13 UTC, swarnadhakad reviewed
LGTM